name: Laravel CI/CD (PRACTICE - FINAL FIX)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    name: CI - Build & Test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_test
          MYSQL_USER: laravel
          MYSQL_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t laravel-practice-test .

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL..."
          for i in {1..30}; do
            if nc -z 127.0.0.1 3306 2>/dev/null; then
              echo "MySQL is ready!"
              break
            fi
            echo "MySQL not ready yet ($i/30)"
            sleep 2
          done

      - name: Install Composer dependencies
        run: |
          docker run --rm -v $(pwd):/var/www -p 9000:9000 laravel-practice-test \
            /bin/sh -c "composer install --no-interaction --prefer-dist --optimize-autoloader"

      - name: Generate App Key & Fix Permissions
        run: |
          docker run --rm -v $(pwd):/var/www laravel-practice-test \
            /bin/sh -c "
              cp .env.example .env &&
              php artisan key:generate --force &&
              mkdir -p storage bootstrap/cache &&
              chmod -R 777 storage bootstrap/cache
            "

      - name: Run Migrations
        run: |
          docker run --rm -v $(pwd):/var/www \
            -e DB_CONNECTION=mysql \
            -e DB_HOST=host.docker.internal \
            -e DB_PORT=3306 \
            -e DB_DATABASE=laravel_test \
            -e DB_USERNAME=laravel \
            -e DB_PASSWORD="${{ secrets.DB_TEST_PASSWORD }}" \
            --add-host=host.docker.internal:host-gateway \
            laravel-practice-test \
            /bin/sh -c "php artisan migrate --force"

      - name: Run Tests
        run: |
          docker run --rm -v $(pwd):/var/www \
            -e DB_CONNECTION=mysql \
            -e DB_HOST=host.docker.internal \
            -e DB_PORT=3306 \
            -e DB_DATABASE=laravel_test \
            -e DB_USERNAME=laravel \
            -e DB_PASSWORD="${{ secrets.DB_TEST_PASSWORD }}" \
            --add-host=host.docker.internal:host-gateway \
            laravel-practice-test \
            /bin/sh -c "php artisan test"

      - name: CI Complete
        run: echo "All tests passed! Ready for CD practice!"

  cd:
    name: CD - Simulate Deployment
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Simulate Production Deployment
        run: |
          echo "CD PRACTICE START"
          echo "Pulling latest image..."
          echo "docker compose down --remove-orphans"
          echo "docker compose up -d"
          echo "Waiting 15s for containers..."
          echo "Running migrations..."
          echo "docker exec laravel_app php artisan migrate --force"
          echo "Optimizing cache..."
          echo "docker exec laravel_app php artisan optimize"
          echo "App live at: http://your-server.com"
          echo "CD PRACTICE COMPLETE"
