name: Laravel CI/CD (Practice)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    name: CI - Build & Test
    runs-on: ubuntu-latest

    services:
      mysql-test:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_test
          MYSQL_USER: laravel
          MYSQL_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install MySQL Client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo_mysql, bcmath, gd
          ini-values: post_max_size=256M, upload_max_filesize=256M

      - name: Install Composer
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate App Key
        run: php artisan key:generate --force

      - name: Set Storage Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Wait for MySQL service
        run: |
          echo "Checking MySQL connection..."
          mysql -h mysql-test -u laravel -p${{ secrets.DB_TEST_PASSWORD }} -e "SELECT 1;"
          echo "MySQL is ready!"

      - name: Run Migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: mysql-test
          DB_PORT: 3306
          DB_DATABASE: laravel_test
          DB_USERNAME: laravel
          DB_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
        run: php artisan migrate --force

      - name: Run Tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: mysql-test
          DB_PORT: 3306
          DB_DATABASE: laravel_test
          DB_USERNAME: laravel
          DB_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
        run: php artisan test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/laravel-practice:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/laravel-practice:latest

  cd:
    name: CD - Simulate Deployment
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Simulate Deployment
        run: |
          echo "Pulling latest Docker image..."
          echo "docker pull ${{ secrets.DOCKER_USERNAME }}/laravel-practice:latest"
          echo "docker compose down && docker compose up -d"
          echo "php artisan migrate --force"
          echo "php artisan optimize"
          echo "CI/CD Practice Complete!"
