name: Laravel CI/CD (Practice)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    name: CI - Build & Test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_test
          MYSQL_USER: laravel
          MYSQL_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost -uroot -proot"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t laravel-practice-test .

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL..."
          for i in {1..30}; do
            docker run --rm --network host laravel-practice-test \
              bash -c "mysql -hmysql -ularavel -p'${{ secrets.DB_TEST_PASSWORD }}' -e 'SELECT 1;'" && break
            echo "MySQL not ready yet, retrying..."
            sleep 2
          done
          echo "MySQL is ready!"

      - name: Install Composer dependencies
        run:
          docker run --rm -v $(pwd):/var/www --network host laravel-practice-test \
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate App Key
        run:
          docker run --rm -v $(pwd):/var/www --network host laravel-practice-test \
          php artisan key:generate --force

      - name: Set Storage Permissions
        run:
          docker run --rm -v $(pwd):/var/www --network host laravel-practice-test \
          bash -c "chmod -R 777 storage bootstrap/cache"

      - name: Run Migrations
        run:
          docker run --rm -v $(pwd):/var/www --network host laravel-practice-test \
          -e DB_CONNECTION=mysql \
          -e DB_HOST=mysql \
          -e DB_PORT=3306 \
          -e DB_DATABASE=laravel_test \
          -e DB_USERNAME=laravel \
          -e DB_PASSWORD="${{ secrets.DB_TEST_PASSWORD }}" \
          php artisan migrate --force

      - name: Run Tests
        run:
          docker run --rm -v $(pwd):/var/www --network host laravel-practice-test \
          -e DB_CONNECTION=mysql \
          -e DB_HOST=mysql \
          -e DB_PORT=3306 \
          -e DB_DATABASE=laravel_test \
          -e DB_USERNAME=laravel \
          -e DB_PASSWORD="${{ secrets.DB_TEST_PASSWORD }}" \
          php artisan test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/laravel-practice:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/laravel-practice:latest

  cd:
    name: CD - Simulate Deployment
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Simulate Deployment
        run: |
          echo "Pulling latest Docker image..."
          echo "docker pull ${{ secrets.DOCKER_USERNAME }}/laravel-practice:latest"
          echo "docker compose down && docker compose up -d"
          echo "php artisan migrate --force"
          echo "php artisan optimize"
          echo "CI/CD Practice Complete!"
