name: Laravel CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      mysql-test:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: testroot
          MYSQL_DATABASE: laravel_test
          MYSQL_USER: laravel
          MYSQL_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
        ports:
          - 3306:3306  # Simplified; Actions uses container port
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Test Image
        run: docker build -t laravel-test .

      - name: Run Composer in Docker
        run: docker run --rm -v $(pwd):/var/www laravel-test composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate App Key
        run: docker run --rm -v $(pwd):/var/www laravel-test php artisan key:generate --force

      - name: Set Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Migrations and Tests in Docker
        env:
          DB_CONNECTION: mysql
          DB_HOST: mysql-test
          DB_PORT: 3306
          DB_DATABASE: laravel_test
          DB_USERNAME: laravel
          DB_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
        run: |
          docker run --rm -v $(pwd):/var/www --network host laravel-test php artisan migrate --force
          docker run --rm -v $(pwd):/var/www --network host laravel-test php artisan test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/laravel-app:${{ github.sha }}, ${{ secrets.DOCKER_USERNAME }}/laravel-app:latest

  cd:
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/laravel  # Your server path
            docker compose -f docker-compose.prod.yml down --remove-orphans
            docker pull ${{ secrets.DOCKER_USERNAME }}/laravel-app:latest
            docker compose -f docker-compose.prod.yml up -d
            docker exec laravel_app php artisan migrate --force
            docker exec laravel_app php artisan optimize:clear
            docker exec laravel_app php artisan optimize
