name: Laravel CI/CD (COMPLETE FIX)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    name: CI - Build & Test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_test
          MYSQL_USER: laravel
          MYSQL_PASSWORD: secret123
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost -uroot -proot"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t laravel-practice-test .

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if timeout 5 mysql -hmysql -ularavel -p'secret123' -e 'SELECT 1;' 2>/dev/null; then
              echo "✅ MySQL is ready!"
              break
            fi
            echo "⏳ MySQL not ready ($i/30)"
            sleep 2
          done

      - name: Install Composer dependencies
        run: |
          docker run --rm -v $(pwd):/var/www laravel-practice-test \
            /bin/sh -c "composer install --no-interaction --prefer-dist --optimize-autoloader"

      - name: Generate App Key
        run: |
          docker run --rm -v $(pwd):/var/www laravel-practice-test \
            /bin/sh -c "cp .env.example .env && php artisan key:generate --force"

      - name: Set Storage Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Migrations
        run: |
          docker run --rm -v $(pwd):/var/www \
            -e DB_CONNECTION=mysql \
            -e DB_HOST=mysql \
            -e DB_PORT=3306 \
            -e DB_DATABASE=laravel_test \
            -e DB_USERNAME=laravel \
            -e DB_PASSWORD=secret123 \
            laravel-practice-test \
            /bin/sh -c "php artisan migrate --force"

      - name: Run Tests
        run: |
          docker run --rm -v $(pwd):/var/www \
            -e DB_CONNECTION=mysql \
            -e DB_HOST=mysql \
            -e DB_PORT=3306 \
            -e DB_DATABASE=laravel_test \
            -e DB_USERNAME=laravel \
            -e DB_PASSWORD=secret123 \
            laravel-practice-test \
            /bin/sh -c "php artisan test"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/laravel-practice:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/laravel-practice:latest

  cd:
    name: CD - Deploy to Server
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/laravel
            docker compose down --remove-orphans
            docker pull ${{ secrets.DOCKER_USERNAME }}/laravel-practice:latest
            docker compose up -d
            sleep 15
            docker exec laravel_app php artisan migrate --force
            echo "🚀 Deployment Complete!"
